import React, { createContext, useContext, useEffect, useMemo, useRef, useState } from "react";
import { supabase } from "../supabaseClient";

const STORAGE_KEY = "jegnit-inventory-data-v1";
const REMOTE_TABLE = "inventory_state_v1";

const PAYMENT_METHODS = ["Cash", "CBE", "Telebirr", "BOA", "Dashen Bank", "Awash Bank"];
const DELIVERY_TYPES = ["Pickup", "Delivery"];

const createId = () => {
  if (typeof crypto !== "undefined" && typeof crypto.randomUUID === "function") {
    return crypto.randomUUID();
  }
  return `id-${Date.now()}-${Math.random().toString(16).slice(2)}`;
};

const InventoryContext = createContext(null);

const TEST_PRODUCT_ID = "b8fc5c6c-d346-456e-8c5d-73f2a231aadf";

// FIX: loadInitialState now also returns transfers; called once via useState lazy init
const loadInitialState = () => {
  try {
    const raw = window.localStorage.getItem(STORAGE_KEY);
    if (!raw) {
      return { products: [], sales: [], replacements: [], transfers: [] };
    }
    const parsed = JSON.parse(raw);
    
    // Filter test dates so they don't load from cache
    let loadedSales = parsed.sales || [];
    loadedSales = loadedSales.filter(s => {
      if (s.date) {
        const isBeforeJune = s.date < "2026-06-01";
        const isFakeSept19 = s.date === "2026-09-19";
        const isFakeOct19 = s.date === "2026-10-19";
        if (isBeforeJune || isFakeSept19 || isFakeOct19) return false;
      }
      return true;
    });

    let loadedProducts = (parsed.products || []).filter(p => p.id !== TEST_PRODUCT_ID);

    return {
      products: loadedProducts,
      sales: loadedSales,
      replacements: parsed.replacements || [],
      transfers: parsed.transfers || [],
    };
  } catch {
    return { products: [], sales: [], replacements: [], transfers: [] };
  }
};

const fetchRemoteState = async () => {
  if (!supabase) return null;
  const { data, error } = await supabase
    .from(REMOTE_TABLE)
    .select("products, sales, replacements, transfers")
    .eq("id", 1)
    .maybeSingle();
  if (error) return null;
  return data || null;
};

/**
 * Merge two arrays by `id`, preferring the remote version when both exist.
 * Records that exist only locally are preserved (never lost due to sync gaps).
 */
const mergeById = (remote = [], local = []) => {
  const map = new Map();
  // First load local records
  for (const item of local) {
    if (item?.id) map.set(item.id, item);
  }
  // Remote records overwrite local (remote is authoritative for shared data)
  for (const item of remote) {
    if (item?.id) map.set(item.id, item);
  }
  return Array.from(map.values());
};

const blockedDuplicateIds = new Set([
  "668e3853-8187-4cd9-ba18-45cfe8b27a73","f503aaa8-4cd5-4a4f-8337-8ebad158bbaf","2847775f-2164-4edb-8230-35e5e271ff0b",
  "762e58ee-0850-4936-b45d-5d0d35714504","65f4b110-55e2-4e03-be8d-f2171d24bbc8","d3fa885d-f20e-43de-b5f7-233271a684ab",
  "7ed51203-1da3-41f3-8363-dcc2deaf8b48","80ed0c29-6697-4073-b77b-febc540d469b","e2b2c205-e232-4288-a312-f39407d289ad",
  "c33e197f-e659-42b6-90ba-61949906a930","b09e1241-0961-415d-b249-80ec5bd431b3","129682a9-7a68-4e04-8b2d-cec10c4a3604",
  "fa20af56-1a4c-452b-a213-0b4381661f3a","49d91b7f-c716-4c1d-ba9a-c00481f0df04","07a487d9-0d09-4fa2-aabe-1ce8faf2b99b",
  "81ebfd22-e02a-42a5-9bcd-8a539ab6897c","2c4536f7-b198-4042-967d-c6338d19289b","6f1d8646-127c-4be4-bc08-c56ed6fbc646",
  "79d5ba70-9fa6-4966-ac69-dc30f2c6249d","05a3e7ee-7f6b-4535-9774-ad5f77281d32","8ae4a1f8-9fdd-4bfb-898e-a129d5e5f1c7",
  "7c397815-70ba-480c-b851-7590299acccf","c7a84953-8491-43fe-baa1-1cb9fb2d0f22","87f9f986-4ab9-40f7-8058-932a98dc1eba",
  "0717e12b-987f-47ef-819f-7ba4b82ad2c0","45e52934-d7a1-41b9-8381-a18443f29717","131851e4-9c71-45e5-b4cd-220cd3b49966",
  "a520c940-37e0-4e42-9a8e-81bc7839dfdf","fecfa833-6bd9-4d76-b661-26754ac93b03","d8b7f1e7-1cb7-4153-a176-0c0c86be574b",
  "7bcc3684-1878-472d-a21e-a023f9a1f788","e2e25a14-c366-40c1-a72d-a123c3755c26","0332d9cc-be05-4c9a-b745-8f01acb40036",
  "4b215f3a-d13c-430c-83e7-7b2b6a96ddb4","73271733-5ece-4674-ae22-68695ca6a223","7a36a224-0778-426a-8135-81313b48ebc0",
  "2051aaa3-6b05-4bf7-bd34-9c7abaf46925","392c6109-3e35-40d9-8682-421ddc708f12","b45f885d-e924-42ef-bd73-6395564ded33",
  "113849e4-82ad-4659-8cf5-4327b12c6cca","458d0295-02fd-4503-96e2-9c0595becd5b","97cc6d4c-38b1-4cdb-b0dd-c656782fee22",
  "1a9425c9-0a55-46b5-acaf-fc5eb21bb849","9e997a29-d5bf-44cf-9dbd-820061bf1069","d1c6d2e0-d125-4fcf-a4db-cc8f27f429b9",
  "4eed9497-eef1-4821-991a-62258d7097f1","2b9b9bd8-266e-4a80-bd63-72e52ff3af68","6e8e1c06-1c52-4649-be98-fcd6ae8eb5e5",
  "ef356166-867b-496c-8b8e-ab854133a91b",
  "ff1be5db-059d-4607-8287-f71f6f2551bf"
]);

const filterTestSales = (salesArray) => {
  return salesArray.filter(s => {
    // Filter hardcoded duplicates generated by manual recovery
    if (s.id && blockedDuplicateIds.has(s.id)) return false;
    
    // If it's a sale record (has date and total), filter test dates
    if (s.date && s.total !== undefined) {
      const isBeforeJune = s.date < "2026-06-01";
      const isFakeSept19 = s.date === "2026-09-19";
      const isFakeOct19 = s.date === "2026-10-19";
      const isFakeAug19 = (s.date === "2026-08-19" && s.productName === "Code 1" && s.total === 1000);
      if (isBeforeJune || isFakeSept19 || isFakeOct19 || isFakeAug19) return false;
    }
    return true;
  });
};

export function InventoryProvider({ children }) {
  // FIX: call loadInitialState exactly once (previously called 3 separate times)
  const [initState] = useState(() => loadInitialState());

  const [products, setProducts] = useState(initState.products);
  const [sales, setSales] = useState(initState.sales);
  const [replacements, setReplacements] = useState(initState.replacements);
  const [transfers, setTransfers] = useState(initState.transfers);
  const [remoteLoaded, setRemoteLoaded] = useState(false);
  const [isSyncing, setIsSyncing] = useState(false);
  const [syncError, setSyncError] = useState(null);

  const isApplyingRemote = useRef(false);

  // Persist everything (including transfers) to localStorage
  useEffect(() => {
    try {
      window.localStorage.setItem(
        STORAGE_KEY,
        JSON.stringify({ products, sales, replacements, transfers })
      );
    } catch {
      // ignore persistence errors
    }
  }, [products, sales, replacements, transfers]);

  // Load from Supabase on first mount — merge with local so no records are lost
  useEffect(() => {
    if (!supabase || remoteLoaded) return;
    (async () => {
      const remote = await fetchRemoteState();
      if (remote) {
        isApplyingRemote.current = true;
        setProducts((local) => mergeById(remote.products || [], local).filter(p => p.id !== TEST_PRODUCT_ID));
        setSales((local) => filterTestSales(mergeById(remote.sales || [], local)));
        setReplacements((local) => mergeById(remote.replacements || [], local));
        setTransfers((local) => mergeById(remote.transfers || [], local));
        setTimeout(() => {
          isApplyingRemote.current = false;
        }, 100);
      }
      setRemoteLoaded(true);
    })();
  }, [remoteLoaded]);

  // Live real-time subscription: listen for updates from other clients in real time
  useEffect(() => {
    if (!supabase) return;

    const channel = supabase
      .channel("public:inventory_state_v1")
      .on(
        "postgres_changes",
        {
          event: "*",
          schema: "public",
          table: REMOTE_TABLE,
          filter: "id=eq.1",
        },
        (payload) => {
          const newRecord = payload.new;
          if (!newRecord) return;

          isApplyingRemote.current = true;
          if (newRecord.products) {
            setProducts((local) =>
              mergeById(newRecord.products || [], local).filter((p) => p.id !== TEST_PRODUCT_ID)
            );
          }
          if (newRecord.sales) {
            setSales((local) => filterTestSales(mergeById(newRecord.sales || [], local)));
          }
          if (newRecord.replacements) {
            setReplacements((local) => mergeById(newRecord.replacements || [], local));
          }
          if (newRecord.transfers) {
            setTransfers((local) => mergeById(newRecord.transfers || [], local));
          }
          setTimeout(() => {
            isApplyingRemote.current = false;
          }, 100);
        }
      )
      .subscribe();

    return () => {
      supabase.removeChannel(channel);
    };
  }, []);

  // Sync to Supabase whenever local state changes (skipped when applying remote updates)
  useEffect(() => {
    if (!supabase || !remoteLoaded) return;
    if (isApplyingRemote.current) return;

    const sync = async () => {
      setIsSyncing(true);
      setSyncError(null);
      try {
        const payload = { id: 1, products, sales, replacements, transfers };
        const { error } = await supabase
          .from(REMOTE_TABLE)
          .upsert(payload, { onConflict: "id" });
        if (error) throw error;
      } catch (err) {
        console.error("Sync error:", err);
        setSyncError(err.message);
      } finally {
        setIsSyncing(false);
      }
    };
    sync();
  }, [products, sales, replacements, transfers, remoteLoaded]);

  // ─── Safe setter helpers ────────────────────────────────────────────────────

  const saveProducts = (updater) => {
    setProducts((prev) => {
      const next = typeof updater === "function" ? updater(prev) : updater;
      return Array.isArray(next) ? next : prev;
    });
  };

  const saveSales = (updater) => {
    setSales((prev) => {
      const next = typeof updater === "function" ? updater(prev) : updater;
      return Array.isArray(next) ? next : prev;
    });
  };

  const saveReplacements = (updater) => {
    setReplacements((prev) => {
      const next = typeof updater === "function" ? updater(prev) : updater;
      return Array.isArray(next) ? next : prev;
    });
  };

  const saveTransfers = (updater) => {
    setTransfers((prev) => {
      const next = typeof updater === "function" ? updater(prev) : updater;
      return Array.isArray(next) ? next : prev;
    });
  };

  const findProductById = (id) => products.find((p) => p.id === id);

  // ─── Product management ─────────────────────────────────────────────────────

  const addOrUpdateProductSize = ({ name, size, price, addMainQty, addShopQty }) => {
    const trimmedName = String(name || "").trim();
    const trimmedSize = String(size || "").trim();
    const mainQty = Number(addMainQty) || 0;
    const shopQty = Number(addShopQty) || 0;

    if (!trimmedName || !trimmedSize) return;

    saveProducts((prev) => {
      const existingIndex = prev.findIndex(
        (p) => p.name.toLowerCase() === trimmedName.toLowerCase()
      );

      if (existingIndex === -1) {
        return [
          ...prev,
          {
            id: createId(),
            name: trimmedName,
            sizes: [
              {
                id: createId(),
                size: trimmedSize,
                price: Number(price) || 0,
                mainStockQty: mainQty,
                shopStockQty: shopQty,
              },
            ],
          },
        ];
      }

      const next = [...prev];
      const product = { ...next[existingIndex] };
      const sizes = [...(product.sizes || [])];
      const sizeIndex = sizes.findIndex(
        (s) => String(s.size).toLowerCase() === trimmedSize.toLowerCase()
      );

      if (sizeIndex === -1) {
        sizes.push({
          id: createId(),
          size: trimmedSize,
          price: Number(price) || 0,
          mainStockQty: mainQty,
          shopStockQty: shopQty,
        });
      } else {
        const existingSize = sizes[sizeIndex];
        sizes[sizeIndex] = {
          ...existingSize,
          price: Number(price) || 0,
          mainStockQty: (Number(existingSize.mainStockQty) || 0) + mainQty,
          shopStockQty: (Number(existingSize.shopStockQty) || 0) + shopQty,
        };
      }

      product.name = trimmedName;
      product.sizes = sizes;
      next[existingIndex] = product;
      return next;
    });
  };

  const updateProductSize = ({
    productId,
    sizeId,
    name,
    size,
    price,
    mainStockQty,
    shopStockQty,
  }) => {
    const trimmedName = String(name || "").trim();
    const trimmedSize = String(size || "").trim();

    saveProducts((prev) =>
      prev.map((p) => {
        if (p.id !== productId) return p;
        return {
          ...p,
          name: trimmedName || p.name,
          sizes: (p.sizes || []).map((s) =>
            s.id === sizeId
              ? {
                  ...s,
                  size: trimmedSize,
                  price: Number(price) || 0,
                  mainStockQty: Number(mainStockQty) || 0,
                  shopStockQty: Number(shopStockQty) || 0,
                }
              : s
          ),
        };
      })
    );
  };

  const deleteProductSize = (productId, sizeId) => {
    saveProducts((prev) =>
      prev
        .map((p) => {
          if (p.id !== productId) return p;
          return { ...p, sizes: (p.sizes || []).filter((s) => s.id !== sizeId) };
        })
        .filter((p) => (p.sizes || []).length > 0)
    );
  };

  const deleteProduct = (productId) => {
    saveProducts((prev) => prev.filter((p) => p.id !== productId));
  };

  // ─── Stock transfer (Admin → pending): validate BEFORE setter ────────────────

  const requestTransfer = ({ productId, sizeId, qty }) => {
    const amount = Number(qty) || 0;
    if (!productId || !sizeId || amount <= 0) {
      throw new Error("Invalid transfer details.");
    }

    // Validate completely BEFORE touching any state
    const product = products.find((p) => p.id === productId);
    if (!product) throw new Error("Product not found.");
    const sizeRow = (product.sizes || []).find((s) => s.id === sizeId);
    if (!sizeRow) throw new Error("Size not found.");
    const currentMain = Number(sizeRow.mainStockQty) || 0;
    if (currentMain < amount) {
      throw new Error(`Not enough items in MAIN stock. Available: ${currentMain}`);
    }

    // Deduct from main stock immediately
    saveProducts((prev) =>
      prev.map((p) => {
        if (p.id !== productId) return p;
        return {
          ...p,
          sizes: (p.sizes || []).map((s) => {
            if (s.id !== sizeId) return s;
            return {
              ...s,
              mainStockQty: (Number(s.mainStockQty) || 0) - amount,
            };
          }),
        };
      })
    );

    // Create pending transfer record
    saveTransfers((prev) => [
      ...prev,
      {
        id: createId(),
        date: new Date().toISOString().slice(0, 10),
        createdAt: new Date().toISOString(),
        productId,
        sizeId,
        productName: product.name,
        size: sizeRow.size,
        qty: amount,
        status: "pending",
        confirmedAt: null,
      },
    ]);
  };

  // Sales person confirms they physically received the items
  const confirmTransfer = (transferId) => {
    const transfer = transfers.find((t) => t.id === transferId);
    if (!transfer) throw new Error("Transfer not found.");
    if (transfer.status === "confirmed") throw new Error("Transfer already confirmed.");

    // Add to shop stock
    saveProducts((prev) =>
      prev.map((p) => {
        if (p.id !== transfer.productId) return p;
        return {
          ...p,
          sizes: (p.sizes || []).map((s) => {
            if (s.id !== transfer.sizeId) return s;
            return {
              ...s,
              shopStockQty: (Number(s.shopStockQty) || 0) + transfer.qty,
            };
          }),
        };
      })
    );

    // Mark transfer as confirmed
    saveTransfers((prev) =>
      prev.map((t) =>
        t.id === transferId
          ? { ...t, status: "confirmed", confirmedAt: new Date().toISOString() }
          : t
      )
    );
  };

  const deleteTransfer = (transferId) => {
    saveTransfers((prev) => prev.filter((t) => t.id !== transferId));
  };

  const deleteTransfersByMonth = (monthStr) => {
    // monthStr format: "YYYY-MM"
    saveTransfers((prev) => prev.filter((t) => !t.date.startsWith(monthStr)));
  };

  // ─── Sales: validate BEFORE setter (fixes throw-in-setter bug) ─────────────

  const recordSale = ({ date, productId, sizeId, qty, paymentMethod, deliveryType, refNum }) => {
    const amount = Number(qty) || 0;
    if (!productId || !sizeId || amount <= 0) {
      throw new Error("Invalid sale details.");
    }

    // Validate completely BEFORE touching any state
    const product = products.find((p) => p.id === productId);
    if (!product) throw new Error("Product not found.");
    const sizeRow = (product.sizes || []).find((s) => s.id === sizeId);
    if (!sizeRow) throw new Error("Size not found.");
    const shopQty = Number(sizeRow.shopStockQty) || 0;
    if (shopQty < amount) {
      throw new Error(`Only ${shopQty} items available in shop stock.`);
    }

    const unitPrice = Number(sizeRow.price) || 0;
    const total = unitPrice * amount;

    // Safe to update state now — no throws inside setters
    saveProducts((prev) =>
      prev.map((p) => {
        if (p.id !== productId) return p;
        return {
          ...p,
          sizes: (p.sizes || []).map((s) => {
            if (s.id !== sizeId) return s;
            return { ...s, shopStockQty: (Number(s.shopStockQty) || 0) - amount };
          }),
        };
      })
    );

    saveSales((prev) => [
      ...prev,
      {
        id: createId(),
        date,
        productId,
        sizeId,
        productName: product.name,
        size: sizeRow.size,
        qty: amount,
        unitPrice,
        total,
        paymentMethod,
        deliveryType,
        refNum: paymentMethod !== "Cash" ? refNum : "",
      },
    ]);
  };

  // ─── Replacements ───────────────────────────────────────────────────────────

  const recordReplacement = ({ saleId, newProductId, newSizeId, qty }) => {
    const amount = Number(qty) || 0;
    if (!saleId || !newProductId || !newSizeId || amount <= 0) {
      throw new Error("Invalid replacement details.");
    }

    const existingSale = sales.find((s) => s.id === saleId);
    if (!existingSale) throw new Error("Original sale not found.");
    if (amount > (Number(existingSale.qty) || 0)) {
      throw new Error("Replacement quantity cannot exceed original sale quantity.");
    }

    const originalProduct = findProductById(existingSale.productId);
    if (!originalProduct) throw new Error("Original product not found.");
    const originalSize = (originalProduct.sizes || []).find(
      (s) => s.id === existingSale.sizeId
    );
    if (!originalSize) throw new Error("Original size not found.");

    const newProduct = findProductById(newProductId);
    if (!newProduct) throw new Error("New product not found.");
    const newSize = (newProduct.sizes || []).find((s) => s.id === newSizeId);
    if (!newSize) throw new Error("New size not found.");

    const currentNewShopQty = Number(newSize.shopStockQty) || 0;
    if (currentNewShopQty < amount) {
      throw new Error(
        `Not enough shop stock for replacement. Available: ${currentNewShopQty}`
      );
    }

    const oldUnit = Number(originalSize.price) || 0;
    const newUnit = Number(newSize.price) || 0;
    const diff = (newUnit - oldUnit) * amount;

    saveProducts((prev) =>
      prev.map((p) => {
        if (p.id !== originalProduct.id && p.id !== newProduct.id) return p;
        return {
          ...p,
          sizes: (p.sizes || []).map((s) => {
            if (p.id === originalProduct.id && s.id === originalSize.id) {
              return { ...s, shopStockQty: (Number(s.shopStockQty) || 0) + amount };
            }
            if (p.id === newProduct.id && s.id === newSize.id) {
              return { ...s, shopStockQty: (Number(s.shopStockQty) || 0) - amount };
            }
            return s;
          }),
        };
      })
    );

    saveSales((prev) => {
      const updated = prev.map((s) => {
        if (s.id !== saleId) return s;
        const remainingQty = (Number(s.qty) || 0) - amount;
        const oldUnitPrice = Number(s.unitPrice) || 0;
        return {
          ...s,
          qty: remainingQty,
          total: remainingQty <= 0 ? 0 : remainingQty * oldUnitPrice,
        };
      });
      return [
        ...updated,
        {
          id: createId(),
          date: existingSale.date,
          productId: newProduct.id,
          sizeId: newSize.id,
          productName: newProduct.name,
          size: newSize.size,
          qty: amount,
          unitPrice: newUnit,
          total: newUnit * amount,
          paymentMethod: existingSale.paymentMethod,
          deliveryType: existingSale.deliveryType,
        },
      ];
    });

    saveReplacements((prev) => [
      ...prev,
      {
        id: createId(),
        date: existingSale.date,
        oldProductName: originalProduct.name,
        oldSize: originalSize.size,
        newProductName: newProduct.name,
        newSize: newSize.size,
        qty: amount,
        customerPays: diff > 0 ? diff : 0,
        refundToCustomer: diff < 0 ? -diff : 0,
      },
    ]);
  };

  // ─── Analytics helpers ──────────────────────────────────────────────────────

  const getLowStockItems = useMemo(
    () => () =>
      products.flatMap((p) =>
        (p.sizes || [])
          .filter((s) => (Number(s.shopStockQty) || 0) <= 3)
          .map((s) => ({ product: p, sizeRow: s }))
      ),
    [products]
  );

  const getDailySummary = (allSales, filters) => {
    const map = new Map();
    for (const s of allSales) {
      if (s.status === "returned") continue; // Option B: exclude returned sales from analytics
      if (filters?.fromDate && s.date < filters.fromDate) continue;
      if (filters?.toDate && s.date > filters.toDate) continue;
      if (filters?.productName && s.productId !== filters.productName) continue;
      const key = s.date;
      const prev = map.get(key) || { date: key, qty: 0, total: 0 };
      prev.qty += Number(s.qty) || 0;
      prev.total += Number(s.total) || 0;
      map.set(key, prev);
    }
    return Array.from(map.values()).sort((a, b) => (a.date < b.date ? -1 : 1));
  };

  const getMonthlySummary = (allSales, filters) => {
    const map = new Map();
    for (const s of allSales) {
      if (s.status === "returned") continue; // Option B: exclude returned sales from analytics
      if (filters?.fromDate && s.date < filters.fromDate) continue;
      if (filters?.toDate && s.date > filters.toDate) continue;
      if (filters?.productName && s.productId !== filters.productName) continue;
      const key = String(s.date || "").slice(0, 7);
      if (!key) continue;
      const prev = map.get(key) || { month: key, qty: 0, total: 0 };
      prev.qty += Number(s.qty) || 0;
      prev.total += Number(s.total) || 0;
      map.set(key, prev);
    }
    return Array.from(map.values()).sort((a, b) => (a.month < b.month ? -1 : 1));
  };

  // ─── Multi-Item Replacement (Option B) ─────────────────────────────────────
  // exchangeItems: [{ productId, sizeId, qty }]
  // returnQty: how many of the original sale item to take back
  const recordMultiReplacement = ({ saleId, returnQty, exchangeItems }) => {
    const retAmount = Number(returnQty) || 0;
    if (!saleId || retAmount <= 0 || !Array.isArray(exchangeItems) || exchangeItems.length === 0) {
      throw new Error("Invalid replacement details.");
    }

    // ── Validate original sale ────────────────────────────────────────────────
    const existingSale = sales.find((s) => s.id === saleId);
    if (!existingSale) throw new Error("Original sale not found.");
    if (retAmount > (Number(existingSale.qty) || 0)) {
      throw new Error("Return quantity cannot exceed original sale quantity.");
    }

    const originalProduct = findProductById(existingSale.productId);
    if (!originalProduct) throw new Error("Original product not found.");
    const originalSize = (originalProduct.sizes || []).find((s) => s.id === existingSale.sizeId);
    if (!originalSize) throw new Error("Original size not found.");

    // ── Validate all exchange items BEFORE touching state ─────────────────────
    const resolvedItems = exchangeItems.map((item, idx) => {
      const amount = Number(item.qty) || 0;
      if (!item.productId || !item.sizeId || amount <= 0) {
        throw new Error(`Exchange item #${idx + 1} is invalid.`);
      }
      const prod = findProductById(item.productId);
      if (!prod) throw new Error(`Exchange item #${idx + 1}: product not found.`);
      const sizeRow = (prod.sizes || []).find((s) => s.id === item.sizeId);
      if (!sizeRow) throw new Error(`Exchange item #${idx + 1}: size not found.`);
      const available = Number(sizeRow.shopStockQty) || 0;
      if (available < amount) {
        throw new Error(
          `Not enough shop stock for ${prod.name} (${sizeRow.size}). Available: ${available}`
        );
      }
      return { prod, sizeRow, amount };
    });

    // ── Calculate money ────────────────────────────────────────────────────────
    const returnedValue = (Number(existingSale.unitPrice) || 0) * retAmount;
    const newItemsValue = resolvedItems.reduce(
      (sum, { sizeRow, amount }) => sum + (Number(sizeRow.price) || 0) * amount,
      0
    );
    const diff = newItemsValue - returnedValue; // positive = customer pays, negative = refund

    // ── Update shop stock ─────────────────────────────────────────────────────
    saveProducts((prev) =>
      prev.map((p) => {
        // Add returned item back to shop stock
        if (p.id === originalProduct.id) {
          return {
            ...p,
            sizes: (p.sizes || []).map((s) => {
              if (s.id !== originalSize.id) return s;
              return { ...s, shopStockQty: (Number(s.shopStockQty) || 0) + retAmount };
            }),
          };
        }
        // Deduct each new item from shop stock
        const matchingItems = resolvedItems.filter((ri) => ri.prod.id === p.id);
        if (matchingItems.length === 0) return p;
        return {
          ...p,
          sizes: (p.sizes || []).map((s) => {
            const match = matchingItems.find((ri) => ri.sizeRow.id === s.id);
            if (!match) return s;
            return { ...s, shopStockQty: (Number(s.shopStockQty) || 0) - match.amount };
          }),
        };
      })
    );

    // ── Mark original sale as returned (Option B) ─────────────────────────────
    // New sale records created for each exchange item
    saveSales((prev) => {
      const updated = prev.map((s) => {
        if (s.id !== saleId) return s;
        return { ...s, status: "returned" }; // Preserve record, just mark it
      });
      const newSaleRecords = resolvedItems.map(({ prod, sizeRow, amount }) => ({
        id: createId(),
        date: existingSale.date,
        productId: prod.id,
        sizeId: sizeRow.id,
        productName: prod.name,
        size: sizeRow.size,
        qty: amount,
        unitPrice: Number(sizeRow.price) || 0,
        total: (Number(sizeRow.price) || 0) * amount,
        paymentMethod: existingSale.paymentMethod,
        deliveryType: existingSale.deliveryType,
        refNum: existingSale.refNum || "",
      }));
      return [...updated, ...newSaleRecords];
    });

    // ── Save replacement history ───────────────────────────────────────────────
    saveReplacements((prev) => [
      ...prev,
      {
        id: createId(),
        date: existingSale.date,
        oldProductName: originalProduct.name,
        oldSize: originalSize.size,
        returnQty: retAmount,
        returnedValue,
        newItemsValue,
        customerPays: diff > 0 ? diff : 0,
        refundToCustomer: diff < 0 ? -diff : 0,
        // Array of new items for display in history
        newItems: resolvedItems.map(({ prod, sizeRow, amount }) => ({
          productName: prod.name,
          size: sizeRow.size,
          qty: amount,
          unitPrice: Number(sizeRow.price) || 0,
        })),
        // Legacy fields for backwards compat with old history display
        newProductName: resolvedItems.map((ri) => ri.prod.name).join(", "),
        newSize: resolvedItems.map((ri) => ri.sizeRow.size).join(", "),
        qty: resolvedItems.reduce((s, ri) => s + ri.amount, 0),
      },
    ]);
  };

  // ─── Reset ──────────────────────────────────────────────────────────────────

  const resetAllData = () => {
    saveProducts([]);
    saveSales([]);
    saveReplacements([]);
    saveTransfers([]);
  };

  // ─── Context value ──────────────────────────────────────────────────────────

  const value = {
    products,
    sales,
    replacements,
    transfers,
    PAYMENT_METHODS,
    DELIVERY_TYPES,
    addOrUpdateProductSize,
    updateProductSize,
    requestTransfer,
    confirmTransfer,
    deleteTransfer,
    deleteTransfersByMonth,
    deleteProduct,
    deleteProductSize,
    recordSale,
    getLowStockItems,
    getDailySummary,
    getMonthlySummary,
    recordReplacement,
    recordMultiReplacement,
    resetAllData,
    isSyncing,
    syncError,
    supabaseConfigured: !!supabase,
  };

  return (
    <InventoryContext.Provider value={value}>{children}</InventoryContext.Provider>
  );
}

export function useInventory() {
  const ctx = useContext(InventoryContext);
  if (!ctx) {
    throw new Error("useInventory must be used within an InventoryProvider");
  }
  return ctx;
}
